### ISSUE TITLE
TODO for next release

### ISSUE THREAD

**Issue by TheLastProject** [TheLastProject/Catima#251]
- [x] Fidme import password-protected zip
- [x] Update to new Voucher Vault export format
- [x] Export Catima data with images as zip
- [x] Import Catima data with images from zip
- [x] Export and import URLs from new catima.app domain

(Yeah, I know GitHub has Projects and stuff but let me be lazy with my TODO list and put my effort into my code instead :wink:)

**Comment by my1stprojekt** [comment]
[] input field for Web-URL
[] option to attach front and back of loyalty card as pictures

Thanks for this beautiful little app. It's the best of its kind I have found and used yet. Sorry for not directly implementing this two things myself, but I have no app-development experience and barely any programming skills (yet).

**Comment by TheLastProject** [comment]
The front and back pictures is already in the codebase so yes, that will be in the next release.

I don't want to add another field, but I do agree that it should be possible to have like clickable URLs or so in the notes field. So for that I created #256.

**Comment by TheLastProject** [comment]
Please take a look at #8 or #89 for discussions about that :)

**Comment by TheLastProject** [comment]
Wow, it seems I may actually be ready for a new release. Just want to wait a bit for #259 and give translators some time to translate the new strings.
